### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by jos0003** [MonashUnitPlanner/springboot-base-gae-java8#46]
We should remove redundant names in the fields. For example `unitCode` should be just `code` if it is in the `Unit` class. However, you can still have `courseCode` in the `Snapshot` class, since it is referring to a different class.

Also I noticed that in the Monash handbook, they use the word `title` instead of the word `name`. So `unitName` should become `title`.

Please read https://github.com/MonashUnitPlanner/newUnitPlanner/blob/typescript/src/types/models.d.ts for detailed field types for each model. By no means it is exhaustive (Unit is missing eftsl for example), and feel free to ask questions on each model so that we can find out ways to improve on it.

Note that sets in JavaScript are defined as JSON objects that have string keys and true values.

**Comment by lorderikir** [comment]
This will be looked at when we build the monPlan API
