### ISSUE TITLE
Respond with total numbers of pages when do a response for pagination

### ISSUE THREAD

**Issue by lorderikir** [MonashUnitPlanner/springboot-base-gae-java8#55]
In order to make a better search for frontend development the api response call for those calls which allows for pagination 

- for example an api call `/api/units?numberPerPage=10&currentPage=5` should return
```
{
    "data": [ ... ]
    "totalNumberOfPages": 20
}
```

**Comment by callistusystan** [comment]
Done in the latest Pull Request
